name: test
on:
  push:
    branches:  
      - sc  
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - run: pnpm install
      - run: pnpm package
      - run: pnpm lint
